// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
     show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB71hK5HNgD-yFtqoSZTGRvlmp7qiu-_yc',
    appId: '1:413820758574:web:dc5b41cd8b46cf4ef24dbf',
    messagingSenderId: '413820758574',
    projectId: 'todo-c28bc',
    authDomain: 'todo-c28bc.firebaseapp.com',
    storageBucket: 'todo-c28bc.appspot.com',
    measurementId: 'G-Y1CJ94CKRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRrdfQ-jFs9YcxMIsfnaZ_0vxyFm5dfUw',
    appId: '1:413820758574:android:a482c19812b8d6e8f24dbf',
    messagingSenderId: '413820758574',
    projectId: 'todo-c28bc',
    storageBucket: 'todo-c28bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTRTu-O_ty06LrtSjeKr0YDzsVFT8Hj4',
    appId: '1:413820758574:ios:056b22c504f3becaf24dbf',
    messagingSenderId: '413820758574',
    projectId: 'todo-c28bc',
    storageBucket: 'todo-c28bc.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrTRTu-O_ty06LrtSjeKr0YDzsVFT8Hj4',
    appId: '1:413820758574:ios:a59af2cd322ad3f8f24dbf',
    messagingSenderId: '413820758574',
    projectId: 'todo-c28bc',
    storageBucket: 'todo-c28bc.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
